# Generated by Django 4.0.3 on 2022-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pgrw_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('lastnames', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
